# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcode', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField()),
                ('nationality', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=5)),
                ('cellphone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_allergy', models.CharField(max_length=100)),
                ('food_allergy', models.CharField(max_length=100)),
                ('other_allergy', models.CharField(max_length=100)),
                ('other_infectious_diseases', models.CharField(max_length=100)),
            ],
        ),
    ]
